### ISSUE TITLE
DateTime doesn't serialize a timestamp

### ISSUE THREAD

**Issue by gmac** [Urigo/graphql-scalars#414]
Using the `DateTime` scalar appears to serialize to a `Date` object, which subsequently prints into the GraphQL response using Date's default `.toString()` implementation. As a result:

**My GraphQL response returns this:** `Fri, 16 Mar 2018 11:50:07 GMT`
**But I was expecting this:** `2018-03-16 11:50:07.000Z`

The relevant code is here – https://github.com/Urigo/graphql-scalars/blob/master/src/scalars/iso-date/DateTime.ts#L35-L49. The choice to always return a `Date` object from the serialize method appears to be intentional, though I can't figure why. Am I overlooking something, or is this a legit issue?

**Comment by ardatan** [comment]
@gmac Could you share a reproduction?

**Comment by gmac** [comment]
@ardatan – sure thing! This sums it up:

**Schema:**

```graphql
scalar DateTime

type Query {
  now: DateTime
}

schema {
  query: Query
}
```

**Resolvers**

```javascript
import { DateTimeResolver } = require('graphql-scalars');
export default {
  DateTime: DateTimeResolver,
  Query: {
    now() {
      return new Date();
    }
  }
};
```

**Query:**

```graphql
query {
  now
}
```

**Result:** the `DateTime` resolver is serializing a JavaScript `Date` object, which has a simple `.toString()` called on it while rendering the GraphQL response.

```json
{
  "data": {
    "now": "Thu Jul 16 2020 10:56:09 GMT-0400 (Eastern Daylight Time)"
  }
}
```

**Expected:** the `DateTime` resolver should serializing a formatted timestamp string.

```json
{
  "data": {
    "now": "2020-07-16T14:56:09.000Z"
  }
}
```

**Comment by danielrearden** [comment]
@gmac Thanks for providing an example. I can't reproduce this issue with the latest version of `graphql-scalars`. I know we changed the DateTime scalar to align with graphql-iso-date [starting with version 1.1.6](https://github.com/Urigo/graphql-scalars/commit/683489993ce27d16077755338ec0cd2dd20a70fb). Maybe you're using an older version?

Here's a sandbox that demonstrates the expected behavior: https://codesandbox.io/s/wizardly-beaver-ekf3s

**Comment by yvann** [comment]
Another way to see this is : The DateTime scalar type cannot parse its serialized value.

**Comment by danielrearden** [comment]
@yvann The scalar's value is serialized as an RFC 3339 date time (such as `"2020-07-29T14:48:52.866Z"`) and it's able to parse such a value if it's submitted as input.

I'm not able to reproduce this issue with the latest version of the library (1.2.2). If you've updated to the latest version and still seeing an issue, it would be helpful to have a Code Sandbox or complete repo with a reproduction.

**Comment by yvann** [comment]
> @yvann The scalar's value is serialized as an RFC 3339 date time (such as `"2020-07-29T14:48:52.866Z"`) and it's able to parse such a value if it's submitted as input.

It's not the behavior I see and not what the code says here https://github.com/Urigo/graphql-scalars/blob/master/src/scalars/iso-date/DateTime.ts#L37
When "serialize" is called, it returns a "Date" object.

By the way, thank you for your fast reply and for the whole library !

**Comment by ardatan** [comment]
It uses Date object internally so your server implementation will serialize it automatically via toJSON method of JS Date.

**Comment by yvann** [comment]
> It uses Date object internally so your server/transport implementation will serialize it via toJSON method of JS Date because you probably use JSON.stringify and the result will be a valid date time string format.

Yes, but still looks wrong to me that we can't "parse" the "serialized" value, it throws an Error. Maybe it's the "parser" that has to accept Date object ?

I see it like this: 
```
parse(value: TExternal): TInternal;
serialize(value: TInternal): TExternal;
```

**Comment by ardatan** [comment]
@yvann You're right! This has been fixed, now `parseValue` accepts `Date` instance.
@gmac Feel free to open a new issue with more details because we couldn't reproduce the issue.

**Comment by yvann** [comment]
🙏 great, thank you for this release !

**Comment by dyst5422** [comment]
This is still an issue when used with introspection. See the code here https://github.com/graphql/graphql-js/blob/master/src/utilities/astFromValue.js#L106-L141 that drives introspection when using default values. The default values need to be serialized. Unfortunately, graphqljs doesn't call JSON.toString() and so this hits the throw clause at the end there.

Still not sure whether this needs to be fixed here to serialize to a string, or on graphqljs to call JSON.toString().

**Comment by dyst5422** [comment]
I find myself back here over a year later reading my own comment. This is still an issue and at this point, I've given up on being able to still have a default value for this scalar.
